# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9fb744d6b5c96a621efe72f0259a6f4bca673d1e0b0602d0b9d0448afa01bb2d8a40ccf06c5cebe04de8f5018f14b33cfb762337e61a120d40a812d10cecaac

test:
  secret_key_base: ec40ad9ba3c11532841c00a5052bd76ac267545d0cf7381dd7c42de0013dd26a3b3117111fc0bacabf0daa3f61b5b72f77277e4bd9e2e0f14649b37d94f09489

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
